default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: fernando
  password: Refreg12
  host: localhost

development:
  <<: *default
  database: database_name_development

test:
  <<: *default
  database: database_name_test

production:
  <<: *default
  database: RedSocial
  url: <%= ENV['DATABASE_URL'] %>
